"""Embodied fly body: NeuroMechFly (MuJoCo) driven by whole-brain descending activity.

The body is FlyGym v2 NeuroMechFly with a tripod CPG controller. The brain does
not yet produce joint-level motor commands directly, so the coupling is made
explicit and honest here:

    left/right descending-neuron firing rate  ->  turn bias + walking gain

This is the same abstraction the NeuroMechFly authors use for their own
connectome-driven demos (descending drive modulates a CPG rather than actuating
joints one by one). Rates come from the live LIF network, so what you see the fly
do is downstream of real connectome dynamics, but the gait itself is generated by
the CPG, not by the connectome.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from flygym.compose import FlatGroundWorld
from flygym.simulation import Simulation
from flygym.utils.math import Rotation3D
from flygym_demo.complex_terrain import (
    CPGController,
    PreprogrammedSteps,
    apply_locomotion_action,
    get_default_locomotion_dof_order,
    make_locomotion_fly,
    make_tripod_cpg_network,
)


@dataclass
class BodyState:
    """What the fly is doing right now, in terms a viewer can read."""

    position: tuple[float, float, float] = (0.0, 0.0, 0.0)
    heading_deg: float = 0.0
    speed_mm_s: float = 0.0
    distance_mm: float = 0.0
    turn_bias: float = 0.0
    drive: float = 0.0
    contacts: list[bool] = field(default_factory=lambda: [False] * 6)
    leg_phases: list[float] = field(default_factory=lambda: [0.0] * 6)
    behavior: str = "standing"
    sim_time_s: float = 0.0


class FlyBody:
    """MuJoCo NeuroMechFly wrapper with a descending-drive controlled CPG."""

    LEG_NAMES = ("lf", "lm", "lh", "rf", "rm", "rh")

    def __init__(
        self,
        *,
        timestep: float = 2e-4,
        camera_res: tuple[int, int] = (720, 980),
        output_fps: int = 24,
        base_frequency: float = 12.0,
    ) -> None:
        self.timestep = timestep
        self.base_frequency = base_frequency

        self.fly = make_locomotion_fly(colorize=True)
        self.camera = self.fly.add_tracking_camera(name="trackcam")
        world = FlatGroundWorld()
        world.add_fly(
            self.fly,
            spawn_position=[0.0, 0.0, 0.5],
            spawn_rotation=Rotation3D("quat", [1.0, 0.0, 0.0, 0.0]),
            add_ground_contact_sensors=True,
        )
        self.sim = Simulation(world, timestep=timestep)
        self.sim.set_renderer(
            cameras=self.camera,
            camera_res=camera_res,
            playback_speed=1.0,
            output_fps=output_fps,
            buffer_frames=False,
        )
        self.sim.reset()

        self.cpg = make_tripod_cpg_network(timestep, intrinsic_frequency=base_frequency)
        self.controller = CPGController(
            cpg_network=self.cpg,
            preprogrammed_steps=PreprogrammedSteps(),
            output_dof_order=get_default_locomotion_dof_order(),
        )

        self._prev_pos = self._thorax_position()
        self._distance = 0.0
        self._speed = 0.0
        self.state = BodyState()
        self._last_frame: np.ndarray | None = None

    # ------------------------------------------------------------------ helpers
    def _thorax_position(self) -> np.ndarray:
        return np.asarray(self.sim.get_body_positions(self.fly.name)[0], dtype=float)

    def _heading_deg(self) -> float:
        rot = self.sim.get_body_rotations(self.fly.name)[0]
        rot = np.asarray(rot, dtype=float).reshape(-1)
        # Body rotations are MuJoCo quaternions (w, x, y, z). Rotate the body
        # forward axis (+x) into world space and project onto the ground plane.
        if rot.size < 4 or not np.any(rot):
            return float(self.state.heading_deg)
        w, x, y, z = rot[:4]
        fwd_x = 1.0 - 2.0 * (y * y + z * z)
        fwd_y = 2.0 * (x * y + w * z)
        return float(np.degrees(np.arctan2(fwd_y, fwd_x)))

    def _contacts(self) -> list[bool]:
        info = self.sim.get_ground_contact_info(self.fly.name)
        # First element is a per-leg boolean/count array.
        arr = np.asarray(info[0]).ravel()
        return [bool(v) for v in arr[:6]]

    # -------------------------------------------------------------------- drive
    def set_descending_drive(self, left_hz: float, right_hz: float,
                             reference_hz: float = 12.0) -> None:
        """Translate left/right descending firing rates into gait parameters.

        Higher total drive walks faster; an imbalance turns the fly toward the
        quieter side, mirroring how unilateral DN activity steers a real fly.
        """
        left = max(0.0, float(left_hz))
        right = max(0.0, float(right_hz))
        total = left + right
        ref = max(1e-6, reference_hz * 2.0)
        drive = float(np.clip(total / ref, 0.0, 1.6))
        bias = 0.0 if total < 1e-6 else float(np.clip((right - left) / total, -1.0, 1.0))

        self.state.drive = drive
        self.state.turn_bias = bias

        # Amplitude gates whether the legs swing at all; frequency sets cadence.
        amp = np.ones(6, dtype=float) * drive
        freq = np.ones(6, dtype=float) * self.base_frequency * (0.35 + 0.65 * drive)
        # Turning: slow the inside legs (left legs are indices 0-2).
        turn = 0.6 * bias
        amp[0:3] *= 1.0 - max(0.0, turn)
        amp[3:6] *= 1.0 - max(0.0, -turn)
        self.cpg.intrinsic_amps = amp
        self.cpg.intrinsic_freqs = freq

        if drive < 0.12:
            self.state.behavior = "standing"
        elif abs(bias) > 0.35:
            self.state.behavior = "turning right" if bias > 0 else "turning left"
        elif drive > 1.0:
            self.state.behavior = "fast walking"
        else:
            self.state.behavior = "walking"

    # --------------------------------------------------------------------- step
    def step(self, n_steps: int = 1) -> bool:
        """Advance the body; returns True if a new camera frame was rendered."""
        rendered = False
        for _ in range(n_steps):
            action = self.controller.step()
            apply_locomotion_action(self.sim, self.fly.name, action)
            self.sim.step()
            if self.sim.render_as_needed():
                rendered = True

        pos = self._thorax_position()
        delta = pos - self._prev_pos
        dt = self.timestep * n_steps
        self._speed = float(np.linalg.norm(delta[:2]) / dt) if dt > 0 else 0.0
        self._distance += float(np.linalg.norm(delta[:2]))
        self._prev_pos = pos

        st = self.state
        st.position = (float(pos[0]), float(pos[1]), float(pos[2]))
        st.heading_deg = self._heading_deg()
        st.speed_mm_s = self._speed
        st.distance_mm = self._distance
        st.contacts = self._contacts()
        st.leg_phases = [float(p % (2 * np.pi)) for p in self.cpg.curr_phases]
        st.sim_time_s = float(self.sim.time)
        return rendered

    def latest_frame(self) -> np.ndarray | None:
        """Render and return the tracking-camera image as an RGB array."""
        frame = self.sim.renderer.mj_renderer
        frame.update_scene(self.sim.mj_data, self.camera.name)
        img = frame.render()
        self._last_frame = img
        return img

    def reset(self) -> None:
        self.sim.reset()
        self.cpg.reset()
        self._prev_pos = self._thorax_position()
        self._distance = 0.0
        self._speed = 0.0
        self.state = BodyState()

    def close(self) -> None:
        self.sim.close()
